
################################
# ###Login 
# post http://localhost:3000/admins/login
# Content-Type: application/json

# {
#     "phone":"1",
#     "password":"2"
# }



# get http://localhost:3000/users/login1
post localhost:3000/users/register
Content-Type: application/json

{
    "fullName":"1",
    "password":"2",
    "phone":"3",
}

